INSERT INTO public.biblical_names ("Name") VALUES
	 ('Aarón'),
	 ('Aaron'),
	 ('Abacuc'),
	 ('Abaddon'),
	 ('Abdias'),
	 ('Abdiel'),
	 ('Abdiou'),
	 ('Abednego'),
	 ('Abel'),
	 ('Abenner');
INSERT INTO public.biblical_names ("Name") VALUES
	 ('Abessa'),
	 ('Abessalom'),
	 ('Abia'),
	 ('Abiah'),
	 ('Abiathar'),
	 ('Abidan'),
	 ('Abiel'),
	 ('Abigaia'),
	 ('Abigaïl'),
	 ('Abigail');
INSERT INTO public.biblical_names ("Name") VALUES
	 ('Abihu'),
	 ('Abijah'),
	 ('Abimael'),
	 ('Abimelech'),
	 ('Abiram'),
	 ('Abisai'),
	 ('Abishag'),
	 ('Abishai'),
	 ('Abital'),
	 ('Abner');
INSERT INTO public.biblical_names ("Name") VALUES
	 ('Abraam'),
	 ('Abraham'),
	 ('Abram 1'),
	 ('Absalom'),
	 ('Achaab'),
	 ('Achab'),
	 ('Achaicus'),
	 ('Achaikos'),
	 ('Achan'),
	 ('''Achashwerosh');
INSERT INTO public.biblical_names ("Name") VALUES
	 ('''Ach''av'),
	 ('Achim 2'),
	 ('Achinoam'),
	 ('Achsah'),
	 ('Adah'),
	 ('Adaiah'),
	 ('Adalia'),
	 ('''Adalya'''),
	 ('Adam'),
	 ('Adamŭ');
INSERT INTO public.biblical_names ("Name") VALUES
	 ('''Adayah'),
	 ('Adina 1'),
	 ('''Adinah'),
	 ('Adino'),
	 ('Adlai'),
	 ('Adonijah'),
	 ('Adoniram'),
	 ('''Adoniyah'),
	 ('Adriel'),
	 ('Agar');
INSERT INTO public.biblical_names ("Name") VALUES
	 ('Agrippa'),
	 ('Ahab'),
	 ('Aharon'),
	 ('Ahasuerus'),
	 ('Ahinoam'),
	 ('Aholibamah'),
	 ('Ahoth'),
	 ('Aithan'),
	 ('''Akhsah'),
	 ('Alexander');
INSERT INTO public.biblical_names ("Name") VALUES
	 ('Alexandros'),
	 ('Allon'),
	 ('Alphaeus'),
	 ('Alphaios'),
	 ('Alvah'),
	 ('Amal 2'),
	 ('Amariah'),
	 ('''Amaryahu'),
	 ('''Amatzyahu'),
	 ('Amaziah');
INSERT INTO public.biblical_names ("Name") VALUES
	 ('Ambakoum'),
	 ('Ambram'),
	 ('Ami 1'),
	 ('Amittai'),
	 ('Ammiel'),
	 ('Amnon'),
	 ('Amos'),
	 ('Amram'),
	 ('Anah'),
	 ('Anaiah');
INSERT INTO public.biblical_names ("Name") VALUES
	 ('Anan 2'),
	 ('Anani'),
	 ('Ananias'),
	 ('Anat 2'),
	 ('Anath 1'),
	 ('Andreas'),
	 ('Andrei'),
	 ('Andrew'),
	 ('Andronicus'),
	 ('Andronikos');
INSERT INTO public.biblical_names ("Name") VALUES
	 ('Anna'),
	 ('Annas'),
	 ('Aod'),
	 ('Apphia'),
	 ('Aquila'),
	 ('Aram 3'),
	 ('Aran 2'),
	 ('Archelaos'),
	 ('Archelaus'),
	 ('Archippos');
INSERT INTO public.biblical_names ("Name") VALUES
	 ('Archippus'),
	 ('Areli'),
	 ('Aretas'),
	 ('Aridai'),
	 ('Arieh'),
	 ('''Ari''el'),
	 ('Ariel'),
	 ('Arihel'),
	 ('Aronne'),
	 ('Artaxerxes');
INSERT INTO public.biblical_names ("Name") VALUES
	 ('Asa'),
	 ('Asaf 1'),
	 ('Asaph'),
	 ('''Asenat'),
	 ('Asenath'),
	 ('Aseneth'),
	 ('Asenneth'),
	 ('Aser'),
	 ('Asher'),
	 ('''Ashtoret');
INSERT INTO public.biblical_names ("Name") VALUES
	 ('Ashtoreth'),
	 ('Asmodaios'),
	 ('Asmodeus'),
	 ('Asnappar'),
	 ('Astarte'),
	 ('Atalyah'),
	 ('Atarah'),
	 ('Athaliah'),
	 ('''Avdi''el'),
	 ('Avenirŭ');
INSERT INTO public.biblical_names ("Name") VALUES
	 ('Avidan'),
	 ('''Avi''el'),
	 ('''Avigayil'),
	 ('Avihu'),
	 ('''Avima''el'),
	 ('''Avimelekh'),
	 ('Aviram'),
	 ('Avishag'),
	 ('''Avishay'),
	 ('Avital');
INSERT INTO public.biblical_names ("Name") VALUES
	 ('''Aviyah'),
	 ('Avner'),
	 ('Avraamŭ'),
	 ('Avraham'),
	 ('Avram'),
	 ('''Avshalom'),
	 ('Azarel'),
	 ('Azariah'),
	 ('Azarias'),
	 ('''Azaryah');
INSERT INTO public.biblical_names ("Name") VALUES
	 ('Azazel'),
	 ('Azaziah'),
	 ('Azazias'),
	 ('''Azazyahu'),
	 ('Azel'),
	 ('Aziel'),
	 ('''Azri''el'),
	 ('Azriel'),
	 ('Azubah'),
	 ('Ba''al');
INSERT INTO public.biblical_names ("Name") VALUES
	 ('Baal'),
	 ('Baal-Zebub'),
	 ('Ba''al Zevuv'),
	 ('Bala 2'),
	 ('Balla'),
	 ('Baltasar'),
	 ('Baltassar'),
	 ('Barak 1'),
	 ('Barnabas'),
	 ('Barouch');
INSERT INTO public.biblical_names ("Name") VALUES
	 ('Bartholomaios'),
	 ('Bartholomei'),
	 ('Bartholomeus'),
	 ('Bartholomew'),
	 ('Baruch'),
	 ('Barukh'),
	 ('Barzillai'),
	 ('Basemath'),
	 ('Basemmath'),
	 ('Bashemath');
INSERT INTO public.biblical_names ("Name") VALUES
	 ('Basmat'),
	 ('Basmath'),
	 ('Bathsheba'),
	 ('Bat-Sheva'),
	 ('Beelzeboul'),
	 ('Beelzebub'),
	 ('Beelzebul'),
	 ('Belial'),
	 ('Belshatzzar'),
	 ('Belshazzar');
INSERT INTO public.biblical_names ("Name") VALUES
	 ('Benaiah'),
	 ('Benayah'),
	 ('Beniamin'),
	 ('Benjamin'),
	 ('Bernice'),
	 ('Bernike'),
	 ('Bethsabée'),
	 ('Bethsabee'),
	 ('Bethuel'),
	 ('Bet''uel');
INSERT INTO public.biblical_names ("Name") VALUES
	 ('Beulah'),
	 ('Bila'),
	 ('Bilha'),
	 ('Bilhah'),
	 ('Binyamin'),
	 ('Bithiah'),
	 ('Bityah'),
	 ('Boaz'),
	 ('Boos'),
	 ('Booz');
INSERT INTO public.biblical_names ("Name") VALUES
	 ('Buz'),
	 ('Caiaphas'),
	 ('Cain'),
	 ('Cainan'),
	 ('Caleb'),
	 ('Canaan'),
	 ('Candace'),
	 ('Carmi'),
	 ('Carpus'),
	 ('Cephas');
INSERT INTO public.biblical_names ("Name") VALUES
	 ('Chaggai'),
	 ('Chaggit'),
	 ('Chaleb'),
	 ('Cham'),
	 ('Chamutal'),
	 ('Chanaan'),
	 ('Chanan'),
	 ('Chananyah'),
	 ('Channah'),
	 ('Chanokh');
INSERT INTO public.biblical_names ("Name") VALUES
	 ('Chavaqquq'),
	 ('Chawwah'),
	 ('Chaza''el'),
	 ('Cheftzi-Bah'),
	 ('Chenaniah'),
	 ('Chizqiyahu'),
	 ('Chloe'),
	 ('Chodesh'),
	 ('Chuldah'),
	 ('Claudia');
INSERT INTO public.biblical_names ("Name") VALUES
	 ('Cleopas'),
	 ('Cleophas'),
	 ('Clopas'),
	 ('Cornelius'),
	 ('Cozbi'),
	 ('Crescens'),
	 ('Cyrus'),
	 ('Dabid'),
	 ('Dalida'),
	 ('Dalila');
INSERT INTO public.biblical_names ("Name") VALUES
	 ('Damaris'),
	 ('Dan 1'),
	 ('Daniel'),
	 ('Danihel'),
	 ('Daniilŭ'),
	 ('Daniyyel'),
	 ('Dareios'),
	 ('Darius'),
	 ('Daryawesh'),
	 ('Dathan');
INSERT INTO public.biblical_names ("Name") VALUES
	 ('Dauid'),
	 ('David'),
	 ('Davidŭ'),
	 ('Dawid'),
	 ('Debbora'),
	 ('Deborah'),
	 ('Deina'),
	 ('Delaiah'),
	 ('Delayahu'),
	 ('Delilah');
INSERT INTO public.biblical_names ("Name") VALUES
	 ('Devorah'),
	 ('Diklah'),
	 ('Dina 1'),
	 ('Dinah'),
	 ('Dionysius'),
	 ('Dorcas'),
	 ('Dorkas'),
	 ('Drousilla'),
	 ('Drusilla'),
	 ('Eder 1');
INSERT INTO public.biblical_names ("Name") VALUES
	 ('Edna'),
	 ('''Ednah'),
	 ('Edom'),
	 ('Efraim'),
	 ('Efrat'),
	 ('''Efrayim'),
	 ('Ehud'),
	 ('Eiran'),
	 ('Eitan'),
	 ('Elah');
