INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Aarón'),
	 ('Aaron'),
	 ('Abacuc'),
	 ('Abaddon'),
	 ('Abdias'),
	 ('Abdiel'),
	 ('Abdiou'),
	 ('Abednego'),
	 ('Abel'),
	 ('Abenner');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Abessa'),
	 ('Abessalom'),
	 ('Abia'),
	 ('Abiah'),
	 ('Abiathar'),
	 ('Abidan'),
	 ('Abiel'),
	 ('Abihu'),
	 ('Abijah'),
	 ('Abimael');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Abimelech'),
	 ('Abiram'),
	 ('Abisai'),
	 ('Abishai'),
	 ('Abner'),
	 ('Abraam'),
	 ('Abraham'),
	 ('Abram 1'),
	 ('Absalom'),
	 ('Achaab');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Achab'),
	 ('Achaicus'),
	 ('Achaikos'),
	 ('Achan'),
	 ('''Achashwerosh'),
	 ('''Ach''av'),
	 ('Achim 2'),
	 ('Adaiah'),
	 ('Adalia'),
	 ('''Adalya''');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Adam'),
	 ('Adamŭ'),
	 ('''Adayah'),
	 ('Adina 1'),
	 ('''Adinah'),
	 ('Adino'),
	 ('Adlai'),
	 ('Adonijah'),
	 ('Adoniram'),
	 ('''Adoniyah');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Adriel'),
	 ('Agrippa'),
	 ('Ahab'),
	 ('Aharon'),
	 ('Ahasuerus'),
	 ('Ahoth'),
	 ('Aithan'),
	 ('Alexander'),
	 ('Alexandros'),
	 ('Allon');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Alphaeus'),
	 ('Alphaios'),
	 ('Alvah'),
	 ('Amal 2'),
	 ('Amariah'),
	 ('''Amaryahu'),
	 ('''Amatzyahu'),
	 ('Amaziah'),
	 ('Ambakoum'),
	 ('Ambram');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Ami 1'),
	 ('Amittai'),
	 ('Ammiel'),
	 ('Amnon'),
	 ('Amos'),
	 ('Amram'),
	 ('Anah'),
	 ('Anaiah'),
	 ('Anan 2'),
	 ('Anani');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Ananias'),
	 ('Anat 2'),
	 ('Anath 1'),
	 ('Andreas'),
	 ('Andrei'),
	 ('Andrew'),
	 ('Andronicus'),
	 ('Andronikos'),
	 ('Annas'),
	 ('Aod');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Aquila'),
	 ('Aram 3'),
	 ('Aran 2'),
	 ('Archelaos'),
	 ('Archelaus'),
	 ('Archippos'),
	 ('Archippus'),
	 ('Areli'),
	 ('Aretas'),
	 ('Aridai');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Arieh'),
	 ('''Ari''el'),
	 ('Ariel'),
	 ('Arihel'),
	 ('Aronne'),
	 ('Artaxerxes'),
	 ('Asa'),
	 ('Asaf 1'),
	 ('Asaph'),
	 ('Aser');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Asher'),
	 ('Asmodaios'),
	 ('Asmodeus'),
	 ('Asnappar'),
	 ('Atalyah'),
	 ('Athaliah'),
	 ('''Avdi''el'),
	 ('Avenirŭ'),
	 ('Avidan'),
	 ('''Avi''el');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Avihu'),
	 ('''Avima''el'),
	 ('''Avimelekh'),
	 ('Aviram'),
	 ('''Avishay'),
	 ('''Aviyah'),
	 ('Avner'),
	 ('Avraamŭ'),
	 ('Avraham'),
	 ('Avram');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('''Avshalom'),
	 ('Azarel'),
	 ('Azariah'),
	 ('Azarias'),
	 ('''Azaryah'),
	 ('Azazel'),
	 ('Azaziah'),
	 ('Azazias'),
	 ('''Azazyahu'),
	 ('Azel');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Aziel'),
	 ('''Azri''el'),
	 ('Azriel'),
	 ('Ba''al'),
	 ('Baal'),
	 ('Baal-Zebub'),
	 ('Ba''al Zevuv'),
	 ('Baltasar'),
	 ('Baltassar'),
	 ('Barak 1');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Barnabas'),
	 ('Barouch'),
	 ('Bartholomaios'),
	 ('Bartholomei'),
	 ('Bartholomeus'),
	 ('Bartholomew'),
	 ('Baruch'),
	 ('Barukh'),
	 ('Barzillai'),
	 ('Beelzeboul');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Beelzebub'),
	 ('Beelzebul'),
	 ('Belial'),
	 ('Belshatzzar'),
	 ('Belshazzar'),
	 ('Benaiah'),
	 ('Benayah'),
	 ('Beniamin'),
	 ('Benjamin'),
	 ('Bethuel');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Bet''uel'),
	 ('Binyamin'),
	 ('Boaz'),
	 ('Boos'),
	 ('Booz'),
	 ('Buz'),
	 ('Caiaphas'),
	 ('Cain'),
	 ('Cainan'),
	 ('Caleb');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Canaan'),
	 ('Carmi'),
	 ('Carpus'),
	 ('Cephas'),
	 ('Chaggai'),
	 ('Chaleb'),
	 ('Cham'),
	 ('Chanaan'),
	 ('Chanan'),
	 ('Chananyah');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Chanokh'),
	 ('Chavaqquq'),
	 ('Chaza''el'),
	 ('Chenaniah'),
	 ('Chizqiyahu'),
	 ('Cleopas'),
	 ('Cleophas'),
	 ('Clopas'),
	 ('Cornelius'),
	 ('Crescens');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Cyrus'),
	 ('Dabid'),
	 ('Dan 1'),
	 ('Daniel'),
	 ('Danihel'),
	 ('Daniilŭ'),
	 ('Daniyyel'),
	 ('Dareios'),
	 ('Darius'),
	 ('Daryawesh');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Dathan'),
	 ('Dauid'),
	 ('David'),
	 ('Davidŭ'),
	 ('Dawid'),
	 ('Delaiah'),
	 ('Delayahu'),
	 ('Diklah'),
	 ('Dionysius'),
	 ('Eder 1');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Edom'),
	 ('Efraim'),
	 ('''Efrayim'),
	 ('Ehud'),
	 ('Eiran'),
	 ('Eitan'),
	 ('Elah'),
	 ('Elam'),
	 ('''El''azar'),
	 ('Elchanan');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Eldad'),
	 ('Eleazar'),
	 ('Elhanan'),
	 ('Eli 1'),
	 ('Eliab'),
	 ('Eliakim'),
	 ('Elias'),
	 ('Eliav'),
	 ('Eliel'),
	 ('''Eli''ezer');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Eliezer'),
	 ('''Elifalet'),
	 ('''Elifelet'),
	 ('Elihu'),
	 ('Elijah'),
	 ('Elioenai'),
	 ('Eliou'),
	 ('Elioud'),
	 ('Eliphalet'),
	 ('Eliphelet');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Elisaie'),
	 ('Eliseus'),
	 ('Elisha'),
	 ('Elishua'),
	 ('Eliud'),
	 ('Eliyyahu'),
	 ('Elkanah'),
	 ('''Elnatan'),
	 ('Elnathan'),
	 ('Elon');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Emmanouel'),
	 ('Emmanuel'),
	 ('Emmanuhel'),
	 ('Enoch'),
	 ('Enok'),
	 ('Enos'),
	 ('Enosh'),
	 ('Epaphras'),
	 ('Epaphroditos'),
	 ('Epaphroditus');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Ephraim'),
	 ('Eran'),
	 ('Erastos'),
	 ('Erastus'),
	 ('Esaias'),
	 ('Esau'),
	 ('''Esaw'),
	 ('Esdras'),
	 ('Ethan'),
	 ('Eutychos');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Eutychus'),
	 ('Evyatar'),
	 ('Ezar'),
	 ('Ezechias'),
	 ('Ezechiel'),
	 ('Ezekias'),
	 ('Ezekiel'),
	 ('Ezer'),
	 ('''Ezra'''),
	 ('Ezra');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Ezras'),
	 ('Felix'),
	 ('Festus'),
	 ('Filippŭ'),
	 ('Finees'),
	 ('Gabriel'),
	 ('Gabrihel'),
	 ('Gad'),
	 ('Gaios'),
	 ('Gaius');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Gamaliel'),
	 ('Gavri''el'),
	 ('Gavriilŭ'),
	 ('Gedaliah'),
	 ('Gedalyahu'),
	 ('Gedeon'),
	 ('Gemariah'),
	 ('Gemaryahu'),
	 ('Gera'),
	 ('Gershom');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Gershon'),
	 ('Gideon'),
	 ('Gid''on'),
	 ('Gilad'),
	 ('Gilead'),
	 ('Giobbe'),
	 ('Goliath'),
	 ('Golyat'),
	 ('Gomer'),
	 ('Habacuc');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Habakkuk'),
	 ('Haggai'),
	 ('Ham'),
	 ('Haman'),
	 ('Hanan 1'),
	 ('Hananiah'),
	 ('Hananias'),
	 ('Hannas'),
	 ('Haran'),
	 ('Havilah');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Hazael'),
	 ('Heber 2'),
	 ('Heli 1'),
	 ('Helias'),
	 ('Helihel'),
	 ('Herod'),
	 ('Herodes'),
	 ('Herodion'),
	 ('Hesekiel'),
	 ('Hevel');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Hezekiah'),
	 ('Hieremias'),
	 ('Hieremihel'),
	 ('Hieu'),
	 ('Hiezecihel'),
	 ('Hillel'),
	 ('Hiob'),
	 ('Hirah'),
	 ('Hiram'),
	 ('Hizkiah');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Hosea'),
	 ('Hosee'),
	 ('Hoshea'),
	 ('Huri'),
	 ('Iachin'),
	 ('Iacob'),
	 ('Iacobus'),
	 ('Iafeth'),
	 ('Iair'),
	 ('Iairos');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Iairus'),
	 ('Iakob'),
	 ('Iakobos'),
	 ('Iakovŭ'),
	 ('Iapheth'),
	 ('Iared'),
	 ('Iason'),
	 ('Ichabod'),
	 ('''Iddo'),
	 ('Iddo');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Iephthae'),
	 ('Iepthae'),
	 ('Ierameel'),
	 ('Ieremahel'),
	 ('Ieremias'),
	 ('Iesous'),
	 ('Iessai'),
	 ('Iesse'),
	 ('Iesus'),
	 ('Iezekiel');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Ikhavod'),
	 ('Ilai'),
	 ('Ilia'),
	 ('Immanuel'),
	 ('Ioab'),
	 ('Ioannes'),
	 ('Ioannŭ'),
	 ('Iob'),
	 ('Ioel'),
	 ('Iohannes');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Iohel'),
	 ('Iona 2'),
	 ('Ionas'),
	 ('Ionathan'),
	 ('Ioram'),
	 ('Iosaphat'),
	 ('Ioseph'),
	 ('Ioses'),
	 ('Iosias'),
	 ('Iosifŭ');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Iosue'),
	 ('Iou'),
	 ('Ioubal'),
	 ('Ioudas'),
	 ('''Ira'''),
	 ('Ira 1'),
	 ('Isaac'),
	 ('Isaak'),
	 ('Isaakŭ'),
	 ('Isaia');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Isaiah'),
	 ('Isaias'),
	 ('Ishmael'),
	 ('Ishmerai'),
	 ('Ishvi'),
	 ('Ismael'),
	 ('Ismahel'),
	 ('Israel'),
	 ('Israhel'),
	 ('Issachar');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Itamar'),
	 ('Ithai'),
	 ('Ithamar'),
	 ('Ithiel'),
	 ('Ittai'),
	 ('''Ittay'),
	 ('Iudas'),
	 ('''Iyyov'),
	 ('Jaala'),
	 ('Jaasau');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Jaasiel'),
	 ('Jabez'),
	 ('Jabin'),
	 ('Jachin'),
	 ('Jacob'),
	 ('Jada 2'),
	 ('Jadon'),
	 ('Jahleel'),
	 ('Jahzeel'),
	 ('Jaír');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Jair'),
	 ('Jairus'),
	 ('James'),
	 ('Jamin'),
	 ('Japheth'),
	 ('Jarah'),
	 ('Jared'),
	 ('Jasiel'),
	 ('Jason'),
	 ('Javan');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Jeconiah'),
	 ('Jedidiah'),
	 ('Jehiel'),
	 ('Jehoash'),
	 ('Jehohanan'),
	 ('Jehoiachin'),
	 ('Jehoiakim'),
	 ('Jehonathan'),
	 ('Jehoram'),
	 ('Jehoshaphat');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Jehu'),
	 ('Jehudi'),
	 ('Jephtha'),
	 ('Jephthah'),
	 ('Jerahmeel'),
	 ('Jeremiah'),
	 ('Jeremiel'),
	 ('Jeremy'),
	 ('Jeriah'),
	 ('Jeroboam');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Jesse'),
	 ('Jesus'),
	 ('Jethro'),
	 ('Joab'),
	 ('Joabe'),
	 ('Joah'),
	 ('Joash'),
	 ('Job'),
	 ('Joel'),
	 ('Johanan');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('John'),
	 ('Joktan'),
	 ('Jonah'),
	 ('Jonas 2'),
	 ('Jonatán'),
	 ('Jonathan'),
	 ('Jorah'),
	 ('Joram'),
	 ('Josaphat'),
	 ('Joseph');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Joses'),
	 ('Joshua'),
	 ('Josiah'),
	 ('Josías'),
	 ('Josias'),
	 ('Jotham'),
	 ('Jubal'),
	 ('Judah'),
	 ('Judas'),
	 ('Jude 1');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Kaiaphas'),
	 ('Kain'),
	 ('Kainan'),
	 ('Kalev 2'),
	 ('Karpos'),
	 ('Kayin 2'),
	 ('Keinan'),
	 ('Kemuel'),
	 ('Kena''an'),
	 ('Kenan 1');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Kenaniah'),
	 ('Kenanyahu'),
	 ('Kephas'),
	 ('Kleopas'),
	 ('Klopas'),
	 ('Koresh'),
	 ('Kreskes'),
	 ('Kyros'),
	 ('Laban'),
	 ('Lael');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Lamech'),
	 ('Lazaros'),
	 ('Lazarus'),
	 ('Lebanah'),
	 ('Lemekh'),
	 ('Lemuel'),
	 ('Leui'),
	 ('Levi'),
	 ('Leviathan'),
	 ('Lewi');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Liwyatan'),
	 ('Lot 1'),
	 ('Loukas'),
	 ('Loukios'),
	 ('Lucas'),
	 ('Lucius'),
	 ('Luka'),
	 ('Luke'),
	 ('Maacah'),
	 ('Maachah');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Ma''akhah'),
	 ('Maaseiah'),
	 ('Ma''aseyah'),
	 ('Machlah'),
	 ('Machli'),
	 ('Madai'),
	 ('Mahalah'),
	 ('Mahali 1'),
	 ('Mahlah'),
	 ('Mahli');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Malachi'),
	 ('Mal''akhi'),
	 ('Manaem'),
	 ('Manahem'),
	 ('Manasseh'),
	 ('Manasses'),
	 ('Marcus'),
	 ('Mardochaios'),
	 ('Mardochée'),
	 ('Mardocheus');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Mardoqueo'),
	 ('Mark'),
	 ('Markos'),
	 ('Mathusalam'),
	 ('Mathusalem'),
	 ('Mattan'),
	 ('Mattaniah'),
	 ('Mattanyahu'),
	 ('Matthaios'),
	 ('Matthan');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Matthei'),
	 ('Mattheus'),
	 ('Matthew'),
	 ('Matthia'),
	 ('Matthias'),
	 ('Mattithiah'),
	 ('Mattithyahu'),
	 ('Mattityahu'),
	 ('Matusalemme'),
	 ('Matusalén');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Medad'),
	 ('Melech'),
	 ('Menachem'),
	 ('Menahem'),
	 ('Menashsheh'),
	 ('Merari'),
	 ('Meshach'),
	 ('Meshullam'),
	 ('Methusalem'),
	 ('Methuselah');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Metushelach'),
	 ('Micah'),
	 ('Micaiah'),
	 ('Micajah'),
	 ('Micha 1'),
	 ('Michaeas'),
	 ('Michael'),
	 ('Michahel'),
	 ('Michaiah'),
	 ('Michaias');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Micheas'),
	 ('Mikha''el'),
	 ('Mikhael'),
	 ('Mikhah'),
	 ('Mikhayahu'),
	 ('Mixailŭ'),
	 ('Mnason'),
	 ('Moab'),
	 ('Moisei'),
	 ('Moisés');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Mordecai'),
	 ('Mordokhay'),
	 ('Mose'),
	 ('Mosè'),
	 ('Moses'),
	 ('Moshe'),
	 ('Mouses'),
	 ('Moyses'),
	 ('Nabouchodonosor'),
	 ('Nabuchodonosor');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Nachum'),
	 ('Nadab'),
	 ('Nadav'),
	 ('Naftali'),
	 ('Nahor'),
	 ('Nahum'),
	 ('Naoum'),
	 ('Naphtali'),
	 ('Narcissus'),
	 ('Natan');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Natanaele'),
	 ('Nathan'),
	 ('Nathanael'),
	 ('Nathanahel'),
	 ('Nathaniel'),
	 ('Nebo'),
	 ('Nebrod'),
	 ('Nebuchadnezzar'),
	 ('Nechemyah'),
	 ('Necoda');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Neemias'),
	 ('Nehemiah'),
	 ('Nekoda'),
	 ('Nereus'),
	 ('Neriah'),
	 ('Netan''el'),
	 ('Netanyahu'),
	 ('Nethaneel'),
	 ('Nethanel'),
	 ('Nethaniah');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Nevukhadnetztzar'),
	 ('Nicanor'),
	 ('Nicodemus'),
	 ('Nikanor'),
	 ('Nikodemos'),
	 ('Nimrod'),
	 ('Noach'),
	 ('Noah 1'),
	 ('Noak'),
	 ('Noe');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Noé'),
	 ('Noè'),
	 ('Nogah'),
	 ('Nymphas'),
	 ('Obadiah'),
	 ('Obed'),
	 ('Oded'),
	 ('Ofir'),
	 ('''Ofrah'),
	 ('Ohad');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Olympas'),
	 ('Omar 2'),
	 ('Omri'),
	 ('Onesimos'),
	 ('Onesimus'),
	 ('Onesiphoros'),
	 ('Onesiphorus'),
	 ('Onisimŭ'),
	 ('Ophir'),
	 ('Ophrah');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Osee'),
	 ('Oshea'),
	 ('Othniel'),
	 ('Ourbanos'),
	 ('Ouri'),
	 ('Ourias'),
	 ('Ouriel'),
	 ('''Ovadyah'),
	 ('Oved'),
	 ('Ozazias');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Ozi'),
	 ('Ozias'),
	 ('Oziel'),
	 ('Ozihel'),
	 ('Pallu'),
	 ('Paltiel'),
	 ('Paul'),
	 ('Paulos'),
	 ('Paulus'),
	 ('Pavelŭ');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Peleg'),
	 ('Penuel'),
	 ('Peretz'),
	 ('Perez'),
	 ('Peter'),
	 ('Petros'),
	 ('Petrŭ'),
	 ('Petrus'),
	 ('Phanouel'),
	 ('Phanuel');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Phanuhel'),
	 ('Phares'),
	 ('Pharez'),
	 ('Phelix'),
	 ('Phestos'),
	 ('Philemon'),
	 ('Philetos'),
	 ('Philetus'),
	 ('Philip'),
	 ('Philippos');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Philippus'),
	 ('Phineas'),
	 ('Phinees'),
	 ('Phinehas'),
	 ('Phunihel'),
	 ('Pinchas'),
	 ('Pontius'),
	 ('Prochoros'),
	 ('Prochorus'),
	 ('Qemu''el');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Rafa''el'),
	 ('Rafahel'),
	 ('Raguel'),
	 ('Raguhel'),
	 ('Ram 1'),
	 ('Raphael'),
	 ('Rauhel'),
	 ('Rehav''am'),
	 ('Rehoboam'),
	 ('Remiel');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Reuben'),
	 ('Reuel'),
	 ('Reuven'),
	 ('Rhagouel'),
	 ('Rhaphael'),
	 ('Rhouben'),
	 ('Ruben'),
	 ('Rufus'),
	 ('Ruvimŭ'),
	 ('Salah 2');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Salathiel'),
	 ('Salathihel'),
	 ('Salomo'),
	 ('Salomón'),
	 ('Salomon'),
	 ('Salomone'),
	 ('Samouel'),
	 ('Sampson 1'),
	 ('Samson'),
	 ('Samuel');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Samuhel'),
	 ('Samuilŭ'),
	 ('Sancheriv'),
	 ('Saoul'),
	 ('Sargon'),
	 ('Satan'),
	 ('Saul'),
	 ('Sem'),
	 ('Sennacherib'),
	 ('Sepeteus');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Seraiah'),
	 ('Seth 1'),
	 ('Shadrach'),
	 ('Shalmaneser'),
	 ('Shamgar'),
	 ('Sharar'),
	 ('Sha''ul'),
	 ('She''alti''el'),
	 ('Shealtiel'),
	 ('Sheba');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Shelach'),
	 ('Shelah'),
	 ('Shelomit'),
	 ('Shelomith'),
	 ('Shelomoh'),
	 ('Shem'),
	 ('Shemaiah'),
	 ('Shema''yah'),
	 ('Shemer'),
	 ('Shemu''el');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Shet'),
	 ('Shiloh'),
	 ('Shimei'),
	 ('Shim''i'),
	 ('Shimon'),
	 ('Shimshon'),
	 ('Silas'),
	 ('Silouanos'),
	 ('Silvanus'),
	 ('Simeon');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Simeonŭ'),
	 ('Simon 1'),
	 ('Simonŭ'),
	 ('Solomon'),
	 ('Stefanŭ'),
	 ('Stephanos'),
	 ('Stephanus'),
	 ('Stephen'),
	 ('Sylas'),
	 ('Symeon');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Talmai'),
	 ('Tammuz'),
	 ('Tekoa'),
	 ('Teman'),
	 ('Terach'),
	 ('Terah'),
	 ('Tertius'),
	 ('Thaddaeus'),
	 ('Thaddaios'),
	 ('Thaddeus');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Theophilus'),
	 ('Thoma'),
	 ('Thomas'),
	 ('Tiglath-Pileser'),
	 ('Timaeus'),
	 ('Timaios'),
	 ('Timée'),
	 ('Timeo'),
	 ('Timeus'),
	 ('Timon');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Timothei'),
	 ('Timotheos'),
	 ('Timotheus'),
	 ('Timothy'),
	 ('Tiras'),
	 ('Titos'),
	 ('Titŭ'),
	 ('Titus'),
	 ('Tobia'),
	 ('Tobiah');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Tobias'),
	 ('Tobit'),
	 ('Tobith'),
	 ('Tovi'),
	 ('Toviyyah'),
	 ('Trophimos'),
	 ('Trophimus'),
	 ('Tzefanyah'),
	 ('Tzidkiyahu'),
	 ('Tzion');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Tzivah'),
	 ('Tzuri''el'),
	 ('Urban'),
	 ('Urbanus'),
	 ('''Uri'),
	 ('Uri'),
	 ('Uriah'),
	 ('Urias'),
	 ('Uriel'),
	 ('Urijah');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('''Uriyah'),
	 ('''Uriy''el'),
	 ('Uzzi'),
	 ('Uzziah'),
	 ('Uzziel'),
	 ('''Uzziyyah'),
	 ('Varnava'),
	 ('Veniaminŭ'),
	 ('Yaakov'),
	 ('Ya''asi''el');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Yachin'),
	 ('Yachle''el'),
	 ('Yachtze''el'),
	 ('Yadon'),
	 ('Yair'),
	 ('Yamin'),
	 ('Ya''rah'),
	 ('Yarav''am'),
	 ('Yared'),
	 ('Yawan');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Yechezkel'),
	 ('Yechi''el'),
	 ('Yedidyah'),
	 ('Yefet'),
	 ('Yeho''ash'),
	 ('Yehochanan'),
	 ('Yehonatan'),
	 ('Yehoram'),
	 ('Yehoshafat'),
	 ('Yehoshua');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Yehoyakhin'),
	 ('Yehoyakim'),
	 ('Yehu'''),
	 ('Yehudah'),
	 ('Yehudi'),
	 ('Yekhonyah'),
	 ('Yerachme''el'),
	 ('Yered'),
	 ('Yeriyahu'),
	 ('Yesha''yahu');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Yeshua'),
	 ('Yiftach'),
	 ('Yirmiyahu'),
	 ('Yishai'),
	 ('Yishma''el'),
	 ('Yishmeray'),
	 ('Yisra''el'),
	 ('Yissakhar'),
	 ('Yitro'),
	 ('Yitzhak');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Yo''ach'),
	 ('Yo''ash'),
	 ('Yoav'),
	 ('Yochanan'),
	 ('Yoel'),
	 ('Yonah'),
	 ('Yonatan'),
	 ('Yorah'),
	 ('Yoram'),
	 ('Yosef');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Yoshiyahu'),
	 ('Yotam'),
	 ('Yuval'),
	 ('Zaboulon'),
	 ('Zabulon'),
	 ('Zaccai'),
	 ('Zacchaeus'),
	 ('Zaccharias'),
	 ('Zaccheus'),
	 ('Zachariah');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Zacharias'),
	 ('Zachary'),
	 ('Zadok'),
	 ('Zakchaios'),
	 ('Zakkai'),
	 ('Zalmon'),
	 ('Zarah'),
	 ('Zaxaria'),
	 ('Zebadiah'),
	 ('Zebedaios');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Zebedee'),
	 ('Zebulon'),
	 ('Zebulun'),
	 ('Zechariah'),
	 ('Zedekiah'),
	 ('Zekharyah'),
	 ('Zelophehad'),
	 ('Zephaniah'),
	 ('Zerach'),
	 ('Zerah');
INSERT INTO public.biblical_masculine_names ("Name") VALUES
	 ('Zevadyah'),
	 ('Zevulun'),
	 ('Ziba 2'),
	 ('Zimri'),
	 ('Zion'),
	 ('Zuriel');
