INSERT INTO public.biblical_feminine_names ("Name") VALUES
	 ('Abia'),
	 ('Abiah'),
	 ('Abigaia'),
	 ('Abigaïl'),
	 ('Abigail'),
	 ('Abijah'),
	 ('Abishag'),
	 ('Abital'),
	 ('Achinoam'),
	 ('Achsah');
INSERT INTO public.biblical_feminine_names ("Name") VALUES
	 ('Adah'),
	 ('Agar'),
	 ('Ahinoam'),
	 ('Aholibamah'),
	 ('''Akhsah'),
	 ('Anah'),
	 ('Anna'),
	 ('Apphia'),
	 ('''Asenat'),
	 ('Asenath');
INSERT INTO public.biblical_feminine_names ("Name") VALUES
	 ('Aseneth'),
	 ('Asenneth'),
	 ('''Ashtoret'),
	 ('Ashtoreth'),
	 ('Astarte'),
	 ('Atalyah'),
	 ('Atarah'),
	 ('Athaliah'),
	 ('''Avigayil'),
	 ('Avishag');
INSERT INTO public.biblical_feminine_names ("Name") VALUES
	 ('Avital'),
	 ('''Aviyah'),
	 ('Azubah'),
	 ('Bala 2'),
	 ('Balla'),
	 ('Basemath'),
	 ('Basemmath'),
	 ('Bashemath'),
	 ('Basmat'),
	 ('Basmath');
INSERT INTO public.biblical_feminine_names ("Name") VALUES
	 ('Bathsheba'),
	 ('Bat-Sheva'),
	 ('Bernice'),
	 ('Bernike'),
	 ('Bethsabée'),
	 ('Bethsabee'),
	 ('Beulah'),
	 ('Bila'),
	 ('Bilha'),
	 ('Bilhah');
INSERT INTO public.biblical_feminine_names ("Name") VALUES
	 ('Bithiah'),
	 ('Bityah'),
	 ('Candace'),
	 ('Chaggit'),
	 ('Chamutal'),
	 ('Channah'),
	 ('Chawwah'),
	 ('Cheftzi-Bah'),
	 ('Chloe'),
	 ('Chodesh');
INSERT INTO public.biblical_feminine_names ("Name") VALUES
	 ('Chuldah'),
	 ('Claudia'),
	 ('Cozbi'),
	 ('Dalida'),
	 ('Dalila'),
	 ('Damaris'),
	 ('Debbora'),
	 ('Deborah'),
	 ('Deina'),
	 ('Delilah');
INSERT INTO public.biblical_feminine_names ("Name") VALUES
	 ('Devorah'),
	 ('Dina 1'),
	 ('Dinah'),
	 ('Dorcas'),
	 ('Dorkas'),
	 ('Drousilla'),
	 ('Drusilla'),
	 ('Edna'),
	 ('''Ednah'),
	 ('Efrat');
INSERT INTO public.biblical_feminine_names ("Name") VALUES
	 ('Elisabet'),
	 ('Elisabeth'),
	 ('Elisabetĭ'),
	 ('Elisheba'),
	 ('Elisheva'),
	 ('Elizabeth'),
	 ('Ephrath'),
	 ('''Ester'),
	 ('Esther'),
	 ('Esthirŭ');
INSERT INTO public.biblical_feminine_names ("Name") VALUES
	 ('Eua'),
	 ('Eunice'),
	 ('Eunike'),
	 ('Euodia'),
	 ('Eva'),
	 ('Eve'),
	 ('Gezabele'),
	 ('Gomer'),
	 ('Hadassah'),
	 ('Hagar');
INSERT INTO public.biblical_feminine_names ("Name") VALUES
	 ('Haggith'),
	 ('Hammoleketh'),
	 ('Hamutal'),
	 ('Hannah'),
	 ('Helah'),
	 ('Hephzibah'),
	 ('Hepzibah'),
	 ('Herodias'),
	 ('Hester'),
	 ('Hiezabel');
INSERT INTO public.biblical_feminine_names ("Name") VALUES
	 ('Hodesh'),
	 ('Hodiah'),
	 ('Hodiyah'),
	 ('Hoglah'),
	 ('Hosanna'),
	 ('Hulda 2'),
	 ('Huldah'),
	 ('Iael'),
	 ('Iahel'),
	 ('Idida');
INSERT INTO public.biblical_feminine_names ("Name") VALUES
	 ('Iedida'),
	 ('Iezabel'),
	 ('Ioanna'),
	 ('Iohanna'),
	 ('Ioudith'),
	 ('Iounia'),
	 ('Iscah'),
	 ('Isebel'),
	 ('Iudith'),
	 ('Iudithŭ');
INSERT INTO public.biblical_feminine_names ("Name") VALUES
	 ('Iunia'),
	 ('Ivah'),
	 ('Izebel'),
	 ('''Izevel'),
	 ('Jael'),
	 ('Jahel'),
	 ('Jecoliah'),
	 ('Jedidah'),
	 ('Jehoaddan'),
	 ('Jehosheba');
INSERT INTO public.biblical_feminine_names ("Name") VALUES
	 ('Jehudijah'),
	 ('Jemima'),
	 ('Jerioth'),
	 ('Jerusha'),
	 ('Jescha'),
	 ('Jézabel'),
	 ('Jezabel'),
	 ('Jezebel'),
	 ('Joanna'),
	 ('Jochebed');
INSERT INTO public.biblical_feminine_names ("Name") VALUES
	 ('Judith'),
	 ('Julia'),
	 ('Junia'),
	 ('Kandake'),
	 ('Kazbi'),
	 ('Keren-Happuch'),
	 ('Keren Happukh'),
	 ('Keturah'),
	 ('Ketzi''ah'),
	 ('Kezia');
INSERT INTO public.biblical_feminine_names ("Name") VALUES
	 ('Keziah'),
	 ('Klaudia'),
	 ('Leah'),
	 ('Leia'),
	 ('Lia 1'),
	 ('Lidia'),
	 ('Lois 1'),
	 ('Lo-Ruhamah'),
	 ('Lydia'),
	 ('Maacah');
INSERT INTO public.biblical_feminine_names ("Name") VALUES
	 ('Maachah'),
	 ('Ma''akhah'),
	 ('Maala'),
	 ('Machalat'),
	 ('Machlah'),
	 ('Maeleth'),
	 ('Magdalene'),
	 ('Magdalina'),
	 ('Mahalath'),
	 ('Mahlah');
INSERT INTO public.biblical_feminine_names ("Name") VALUES
	 ('Mara 1'),
	 ('Maria'),
	 ('Mariam'),
	 ('Martha'),
	 ('Mary'),
	 ('Meheitav''el'),
	 ('Mehetabel'),
	 ('Mehitabel'),
	 ('Melcha'),
	 ('Melchol');
INSERT INTO public.biblical_feminine_names ("Name") VALUES
	 ('Merab 1'),
	 ('Merav'),
	 ('Merob'),
	 ('Meshullemet'),
	 ('Meshullemeth'),
	 ('Micaiah'),
	 ('Micajah'),
	 ('Michaiah'),
	 ('Michal 2'),
	 ('Michol');
INSERT INTO public.biblical_feminine_names ("Name") VALUES
	 ('Mikhal'),
	 ('Mikhayahu'),
	 ('Milcah'),
	 ('Milkah'),
	 ('Miriam'),
	 ('Na''amah'),
	 ('Naamah'),
	 ('Na''omi'),
	 ('Naomi 1'),
	 ('Noa 1');
INSERT INTO public.biblical_feminine_names ("Name") VALUES
	 ('No''ah'),
	 ('Noah 2'),
	 ('Noemi'),
	 ('Noemin'),
	 ('Nympha'),
	 ('Oholibamah'),
	 ('''Orpah'),
	 ('Orpah'),
	 ('Orpha'),
	 ('Peninnah');
INSERT INTO public.biblical_feminine_names ("Name") VALUES
	 ('Persis'),
	 ('Phebe'),
	 ('Phoebe'),
	 ('Phoibe'),
	 ('Prisca'),
	 ('Priscilla'),
	 ('Priska'),
	 ('Priskilla'),
	 ('Pu''ah'),
	 ('Puah');
INSERT INTO public.biblical_feminine_names ("Name") VALUES
	 ('Rachel'),
	 ('Rahab'),
	 ('Rahel'),
	 ('Rebecca'),
	 ('Rebekah'),
	 ('Reumah'),
	 ('Rhachel'),
	 ('Rhebekka'),
	 ('Rhoda'),
	 ('Rhode');
INSERT INTO public.biblical_feminine_names ("Name") VALUES
	 ('Rhouth'),
	 ('Rivqah'),
	 ('Rizpah'),
	 ('Rut'),
	 ('Ruth 1'),
	 ('Ruthĭ'),
	 ('Saffira'),
	 ('Salome'),
	 ('Sappheire'),
	 ('Sapphira');
INSERT INTO public.biblical_feminine_names ("Name") VALUES
	 ('Sara'),
	 ('Sarah'),
	 ('Sarai'),
	 ('Sarra'),
	 ('Sarrha'),
	 ('Seera'),
	 ('Seffora'),
	 ('Selah'),
	 ('Sepphora'),
	 ('Sheerah');
INSERT INTO public.biblical_feminine_names ("Name") VALUES
	 ('Shelomit'),
	 ('Shelomith'),
	 ('Sherah'),
	 ('Shifra'),
	 ('Shiloh'),
	 ('Shim''at'),
	 ('Shimeath'),
	 ('Shiphrah'),
	 ('Shoshannah'),
	 ('Shulamite');
INSERT INTO public.biblical_feminine_names ("Name") VALUES
	 ('Shulammit'),
	 ('Shulammite'),
	 ('Silpa'),
	 ('Sousanna'),
	 ('Susanna'),
	 ('Susannah'),
	 ('Syntyche'),
	 ('Tabita'),
	 ('Tabitha'),
	 ('Tahpenes');
INSERT INTO public.biblical_feminine_names ("Name") VALUES
	 ('Talitha'),
	 ('Tamar'),
	 ('Taphath'),
	 ('Thamar'),
	 ('Themar'),
	 ('Thersa'),
	 ('Tirtzah'),
	 ('Tirzah'),
	 ('Tryphaina'),
	 ('Tryphena');
INSERT INTO public.biblical_feminine_names ("Name") VALUES
	 ('Tryphosa'),
	 ('Tzeruyah'),
	 ('Tzillah'),
	 ('Tzipporah'),
	 ('Tzivyah'),
	 ('Vashti'),
	 ('Washti'),
	 ('Yael'),
	 ('Yedidah'),
	 ('Yeho''addan');
INSERT INTO public.biblical_feminine_names ("Name") VALUES
	 ('Yehosheva'),
	 ('Yehudit'),
	 ('Yehudiyah'),
	 ('Yekholyah'),
	 ('Yemima'),
	 ('Yeri''ot'),
	 ('Yerushah'),
	 ('Yiskah'),
	 ('Yocheved'),
	 ('Zebidah');
INSERT INTO public.biblical_feminine_names ("Name") VALUES
	 ('Zebudah'),
	 ('Zelpha'),
	 ('Zeresh'),
	 ('Zeruiah'),
	 ('Zevidah'),
	 ('Zibiah'),
	 ('Zillah'),
	 ('Zilpa'),
	 ('Zilpah'),
	 ('Zipporah');
